### ISSUE TITLE
Is this repo still maintained?

### ISSUE THREAD

**Issue by hateonion** [microsoft/TypeScript-Handbook#1000]
Well, I found there are a lot of pull requests left and those are really good fixes. The latest merged pull request is back to Feb. Just doubt about that is Typescript-Handbook still maintained?

**Comment by shamilDzhakeev** [comment]
Maybe they want to support new handbook instead this? For example this: 
https://github.com/microsoft/TypeScript-New-Handbook

**Comment by orta** [comment]
Maintenance kinda happens here and there in batches - TS's popularity means the team gets stretched a lot just trying to keep pace, but I'll try keep on top of some of these repos.
