### ISSUE TITLE
Fix the typo in left menu

### ISSUE THREAD

**Issue by sunndeath** [microsoft/TypeScript-Handbook#1011]
Hi,
Fix the typo, please (doubled menu item):
Project Configuration / tsconfig.json

![Annotation 2019-04-10 135835](https://user-images.githubusercontent.com/8881978/55873712-0267ed00-5b99-11e9-81e3-6bf1a684b3b8.jpg)

**Comment by orta** [comment]
This looks fixed now on my staging site 👍
