### ISSUE TITLE
Document `ThisType<T>`

### ISSUE THREAD

**Issue by trusktr** [microsoft/TypeScript-Handbook#1037]
Continuing from https://github.com/microsoft/TypeScript-Handbook/issues/649, there doesn't seem to be a link to the "Utility Types" page in the sidebar menu, so it is hidden.

**Comment by Retsam** [comment]
Yup, there's already #994 tracking this.

**Comment by karlhorky** [comment]
@trusktr I think this can be closed, can't it? Since it's a dupe of #994?

**Comment by orta** [comment]
Yep @karlhorky  just sent the fix and it's being deployed now
