### ISSUE TITLE
Parameter Decorators Take 3 Arguments (Not 2)

### ISSUE THREAD

**Issue by SlurpTheo** [Microsoft/TypeScript-Handbook#105]
[Link to handbook](https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Decorators.md#parameter-decorators) -- Explicitly mentions 2 arguments and then only shows the use of 2 arguments in the example as well.

From the lib.d.ts (I checked 1.6.2 & 1.8.0 versions) it seems like `propertyKey` is the one missing from the documentation:
```javascript
declare type ParameterDecorator = (target: Object, propertyKey: string | symbol, parameterIndex: number) => void;
```

**Comment by mhegazy** [comment]
thanks! can you give it another try now

**Comment by SlurpTheo** [comment]
@mhegazy Now the sample looks good, but the text above the sample still says:


The expression for the parameter decorator will be called as a function at runtime, with the following ***two*** arguments:

1. The function containing the decorated parameter.
***2***. The ordinal index of the parameter in the function's parameter list.

**Comment by mhegazy** [comment]
Sorry about that, here is take 2. give it another look.

**Comment by SlurpTheo** [comment]
Looks good!
:thumbsup:
