### ISSUE TITLE
Possible typo in readme?

### ISSUE THREAD

**Issue by VictorioBerra** [microsoft/TypeScript-Handbook#1052]
You will have to excuse me as I am a beginner looking through the handbook but shouldnt the [first example in Module Augmentation](https://github.com/microsoft/TypeScript-Handbook/blob/master/pages/Declaration%20Merging.md#module-augmentation) be .ts files?

**Comment by sasurau4** [comment]
I confirm this issue is fixed by https://github.com/microsoft/TypeScript-Handbook/commit/d457beacc0a9130661938210e2d6351955997f2a
