### ISSUE TITLE
Add section on object literals

### ISSUE THREAD

**Issue by karlhorky** [microsoft/TypeScript-Handbook#1054]
Although object literals are mentioned throughout the docs and release notes in various places (ex. [pages/Type Compatibility.md](https://github.com/microsoft/TypeScript-Handbook/blob/524ed56fe88045a0234e84dc6838b9c5e202d4c5/pages/Type%20Compatibility.md), [pages/Type Checking JavaScript Files.md](https://github.com/microsoft/TypeScript-Handbook/blob/112bfeac2c362997102f6554dce55759606de848/pages/Type%20Checking%20JavaScript%20Files.md)), they are not explicitly documented anywhere (such as [Object Types](https://flow.org/en/docs/types/objects/#toc-object-type-syntax) from the Flow documentation).

Would the TypeScript team be open to having these documented explicitly somewhere? Such as on the [Basic Types](https://github.com/microsoft/TypeScript-Handbook/blob/10277990ce79c251449c83f87fecae98cb42a40a/pages/Basic%20Types.md#object) page in the Object section?

Actually, come to think of it, it would be good to have a section on type aliases too... they are also mentioned often without their own area in the beginners material...

**Comment by orta** [comment]
This is a good idea, it's worth checking the new handbook to see if that's still an issue: https://github.com/microsoft/TypeScript-new-Handbook

**Comment by karlhorky** [comment]
Ah wow, cool! The new docs are looking great. I'll use these as a reference for the course material I'm writing.

I suppose we can probably close this, since these are now both being documented:

- [Object Literals: (now called Object Types)](https://microsoft.github.io/TypeScript-New-Handbook/everything/#object-types)
- [Type Aliases](https://microsoft.github.io/TypeScript-New-Handbook/everything/#type-aliases)
