### ISSUE TITLE
Document missing utility types

### ISSUE THREAD

**Issue by karlhorky** [microsoft/TypeScript-Handbook#1060]
#798 and #801 added [a Utility Types page](https://www.typescriptlang.org/docs/handbook/utility-types.html).

It would be nice if the documentation here was comprehensive, with most common utility types.

I was thinking of `ReadonlyArray` and such (but those are covered by https://github.com/microsoft/TypeScript-Handbook/issues/1023).

There's a "comprehensive list" here, although I don't think it's comprehensive either:

https://codewithstyle.info/Comprehensive-list-of-useful-built-in-types-in-TypeScript/

**Comment by jpelton-stroud** [comment]
Not sure when it changed (possibly with the closing of #798), but it looks like the types cited by [CodeWithStyle](https://codewithstyle.info/Comprehensive-list-of-useful-built-in-types-in-TypeScript/) are now included in the [Utility Types page](https://github.com/microsoft/TypeScript-Handbook/blob/master/pages/Utility%20Types.md).

Browsing through [lib.es2015.d.ts](https://github.com/microsoft/TypeScript/blob/master/lib/lib.es2015.d.ts), I (admittedly somewhere between "novice" & "intermediate") don't see anything ts-specific that I would consider "general/common use".  Should this issue be considered closed, or am I missing something obvious?

**Comment by karlhorky** [comment]
I guess it looks like the types are included now, so I will close :)

Thanks for the heads up @jpelton-stroud !
