### ISSUE TITLE
Resolve large font size in handbook documentation

### ISSUE THREAD

**Issue by justinpage** [microsoft/TypeScript-Handbook#1062]
In reference to #1061 

The following address is showing a large font for import resolutions:

https://www.typescriptlang.org/docs/handbook/module-resolution.html#path-mapping

Instead of using an ordered list within a bullet point, bring the subject line to the parent level and then use an ordered list.

Screenshot below for reference:

<img width="887" alt="Screen Shot 2019-07-05 at 5 29 55 PM" src="https://user-images.githubusercontent.com/3615935/60749140-9b18c980-9f4a-11e9-8e01-d3e01d8708af.png">

As we can see, the font is much larger than the rest of the documentation.

**Comment by orta** [comment]
We got a PR fixing this I believe 👍
