### ISSUE TITLE
Broken link in Compiler Options html

### ISSUE THREAD

**Issue by laedit** [microsoft/TypeScript-Handbook#1077]
At the bottom of the [Compiler Options page](https://www.typescriptlang.org/docs/handbook/compiler-options.html), the tsconfig.json link leads to a 404 with https://www.typescriptlang.org/docs/handbook/tutorials/tsconfig-json.html.

The right link is https://www.typescriptlang.org/docs/handbook/tsconfig-json.html.

Since the tsconfig.json.md source is in the tutorials folder, I don't know if it's the link that is broken or if the source must be published.

**Comment by neilbryson** [comment]
I tried doing this change

```diff
-* Setting compiler options in [`tsconfig.json`](./tutorials/tsconfig.json.md) files.
+* Setting compiler options in [`tsconfig.json`](./tsconfig.json.md) files.
```

Link in the website will work fine but navigation using the Markdown version will be broken instead.
