### ISSUE TITLE
update http://www.typescriptlang.org/Handbook

### ISSUE THREAD

**Issue by robstoll** [Microsoft/TypeScript-Handbook#109]
I first had a read through the above mentioned website before looking in the language spec and then realised that a lot of the syntax and concepts described on the above mentioned website is out-of-date, already deprecated respectively. For instance, it does still use the term internal module instead of namespace or uses the `import ... require` instead of `import ... from`.
IMO the website should either be updated or a notice should be shown that it is outdated and one should have a look at the language spec

**Comment by cfebs** [comment]
:+1: 

Just inquired in `#typescript` about this, while exploring it was very difficult to actually get a hold of current syntax or best practices. Was constantly cross referencing w/ the spec and changelog.

**Comment by mhegazy** [comment]
We are actually in the process to updating the website, hopefully have a new one within the next few weeks. This is mainly to update the documentation. sorry for the outdated content, and hopefully we have this issue resolved soon.

**Comment by OlsonDev** [comment]
Any update on this? I feel like I wasted a lot of time reading the entire handbook over Christmas break; when I actually got my hands dirty, I realized *a lot* had changed since the last time the handbook was updated. I agree, an "outdated" notice should be put on the handbook till someone has time to fully update it.

**Comment by jpetitte** [comment]
I had the same issue last year (until I figured out that the wiki here is up to date). This is a serious issue, and I suspect it prevents a lot of beginners from being successful with the language.

**Comment by tpennetta** [comment]
:+1: I spent a lot of time reading, and developing using the "Handbook" and tons of important features are out-dated or just not present. I found this wiki just as others have said.

**Comment by mhegazy** [comment]
Sorry for the delay, but we have rolled out a new website today, see https://blogs.msdn.microsoft.com/typescript/2016/03/24/new-typescript-website/.

Docs should be updated more frequently moving forward.
