### ISSUE TITLE
"Namespaces and modules" section links are dead

### ISSUE THREAD

**Issue by omefire** [Microsoft/TypeScript-Handbook#112]
When reading through the "namespaces and modules" section, I noticed that links to modules and namespaces were dead.

https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Namespaces%20and%20Modules.md

**Comment by DanielRosenwasser** [comment]
Hey @omefire they're intentionally pointing to the html output for now; we're planning on having an automated conversion in the future. Sorry about that.

**Comment by omefire** [comment]
OK, I see.

**Comment by DanielRosenwasser** [comment]
This is annoying enough for the interim that I'm fixing this in #114.
