### ISSUE TITLE
Array Types example error

### ISSUE THREAD

**Issue by MyErpSoft** [Microsoft/TypeScript-Handbook#118]
When reading `Array Types` at https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Interfaces.md  .  I noticed that :

In this example, `length`'s type does not match the string index's type, and the type-checker gives an error:

```ts
interface NumberDictionary {
    [index: string]: number;
    length: number;    // ok, length is a number
    name: string;      // error, the type of 'name' is not a subtype of the indexer
}
```

I think this should be changed:

In this example, `name`'s type does not match the number index's type, and the type-checker gives an error:

```ts
interface NumberDictionary {
    [index: string]: number;
    length: number;    // ok, length is a number
    name: string;      // error, the type of 'name' is not a subtype of the indexer
}
```

Sorry, my English is very bad. :-)

**Comment by DanielRosenwasser** [comment]
Hi there @MyErpSoft, I'm not sure what you mean. `length`'s type is `number`, which satisfies the string index signature type (`number`), so I don't see the problem with the code as it exists.

Additionally, your second code sample is exactly the same as your first. That might have been a copy/paste error.

**Comment by zhongsp** [comment]
@DanielRosenwasser  He's going to point out that there's a typo here:
Change:
> In this example, `length`'s type does not match the numb...


To
> In this example, `name`'s type does not match the numb...

:)

**Comment by DanielRosenwasser** [comment]
Ah! I missed that. Sorry @MyErpSoft, I should have read more closely.

As a heads up, you can make it more obvious that you're quoting something by putting a `>` in front of it. See "Blockquotes" on [GitHub's Markdown Guide](https://guides.github.com/features/mastering-markdown/).

**Comment by DanielRosenwasser** [comment]
Should be fixed now. Thanks for finding these errors!
