### ISSUE TITLE
Broken link in the Compiler Options page

### ISSUE THREAD

**Issue by RaglandCodes** [microsoft/TypeScript-Handbook#1323]
In the option `baseUrl`, in [this page](https://www.typescriptlang.org/docs/handbook/compiler-options.html), the link in the description is broken.

This is the URL: https://www.typescriptlang.org/docs/handbook/docs/handbook/module-resolution.html#base-url

The problem is that "docs/handbook/" appears twice in the link.

**Comment by orta** [comment]
Thanks, that'll get updated in the next deploy!
https://github.com/microsoft/TypeScript-Website/commit/26bb41eeed9e0cb8cdcebee1097e8165c48e19fd
