### ISSUE TITLE
create project fail

### ISSUE THREAD

**Issue by guohuijuan1** [microsoft/TypeScript-Handbook#1324]
![image](https://user-images.githubusercontent.com/54808661/82472604-08016780-9afb-11ea-9e07-c14486a03704.png)
![image](https://user-images.githubusercontent.com/54808661/82473377-0d12e680-9afc-11ea-9449-644742c23e05.png)
![image](https://user-images.githubusercontent.com/54808661/82473451-274cc480-9afc-11ea-8256-5975fcab7d56.png)

**Comment by orta** [comment]
This is related to create-react-app and typescript, and not really the TypeScript handbook - I'd recommend reading the docs for create-react-app
