### ISSUE TITLE
Outdated link at end of handbook for typescriptlang.org

### ISSUE THREAD

**Issue by mhegazy** [Microsoft/TypeScript-Handbook#140]
_From @bartvanderwal on December 19, 2015 0:56_

Hi,
Could you update a link? I think it's great that you're on GitHub now, instead of on Codeplex. However I just read a large part of your handbook at:
http://www.typescriptlang.org/Handbook

The handbook is pretty great, but at the end of it, it still points users to the old CodePlex issues page for issues:
https://typescript.codeplex.com/wikipage?title=https%3a%2f%2fgithub.com%2fMicrosoft%2fTypeScript%2fissues

The outdated link is in the word `here` in the very last sentence of the page:
`Please post a comment **here** if there's a pattern you'd like to see documented! We'll add to this as we can.`

I guess the link now needs to be:
https://github.com/Microsoft/TypeScript/issues/new

Or is there a separate place to put issues with documentation? Because I guess this issue itself then also needs to go there :).

_Copied from original issue: Microsoft/TypeScript#6166_

**Comment by mhegazy** [comment]
_From @DanielRosenwasser on December 19, 2015 1:32_

We're planning on relaunching the handbook soon. You can read a more up-to-date version on https://GitHub.com/Microsoft/TypeScript-Handbook and also file issues there.

**Comment by mhegazy** [comment]
We have just published an updated site, see https://blogs.msdn.microsoft.com/typescript/2016/03/24/new-typescript-website/.

Documentation should be updated more frequently.

**Comment by bartvanderwal** [comment]
https://blogs.msdn.microsoft.com/typescript/2016/03/24/new-typescript-website/ -> "We’re sorry, but we can’t find the page you’re looking for." 


Verstuurd vanaf mijn iPhone

**Comment by mhegazy** [comment]
@bartvanderwal looks like a bug with the bloging system. Can you try again now?

**Comment by bartvanderwal** [comment]
@mhegazy Yes, it's working now!
