### ISSUE TITLE
Minor language error in the handbook

### ISSUE THREAD

**Issue by mhegazy** [Microsoft/TypeScript-Handbook#143]
_From @Romke-vd-Meulen on January 26, 2016 16:5_

From the [handbook](http://www.typescriptlang.org/Handbook#classes-privatepublic-modifiers), section "Parameter properties":

```
The properties let you can create and initialize a member in one step.
```

_Copied from original issue: Microsoft/TypeScript#6624_

**Comment by DanielRosenwasser** [comment]
This is already fixed. The current text is:

> This turns out to be a very common practice. *Parameter properties* let you create and initialize a member in one place.

**Comment by mhegazy** [comment]
@Romke-vd-Meulen we are in the process of updating the TypeScriptLang.org to host the handbook from this repo, instead of the static html files it has now. so the new documentation should be available online soon.
