### ISSUE TITLE
Button and TextBox should extend SelectableControl?

### ISSUE THREAD

**Issue by cnishina** [Microsoft/TypeScript-Handbook#144]
If I'm reading this document correctly, the `Button` and `TextBox` extend `SelectableControl` and the `select` method shown for `Button` and `TextBox` are implementations of the interface? 

pages/Interfaces.md
```
interface SelectableControl extends Control {
    select(): void;
}

class Button extends Control {
    select() { }
}

class TextBox extends Control {
    select() { }
}

class Image extends Control {
}

class Location {
    select() { }
}
```

> The 'Button' and 'TextBox' classes are subtypes of 'SelectableControl' (because they both inherit from 'Control' and have a 'select' method), but the 'Image' and 'Location' classes are not.`

**Comment by cnishina** [comment]
After reading that paragraph a few more times... not an issue.

**Comment by adityamenonsrijan** [comment]
@cnishina I'm still not able to understand why it's not an issue. Looks like someone else also has an open PR about this: https://github.com/Microsoft/TypeScript-Handbook/issues/366 Could you elaborate a bit on what you figured out please?
