### ISSUE TITLE
Add a version incongruity warning.

### ISSUE THREAD

**Issue by madroneropaulo** [Microsoft/TypeScript-Handbook#150]
It would be handy to warn people about some incongruities between the handbook information and the different typescript versions, like "this handbook refers to typescript 1.5, for newer versions, please seee [latest TypeScript Language Specification](https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md)." Specially if the handbook updates are not planned to be released soon.  Issue related to #139

**Comment by mhegazy** [comment]
The handbook has been updated, see https://blogs.msdn.microsoft.com/typescript/2016/03/24/new-typescript-website/. moving forward, we should be updating the handbook along with the release.
