### ISSUE TITLE
Where can I get the system to build the site like typescriptlang.org?

### ISSUE THREAD

**Issue by KostyaTretyak** [Microsoft/TypeScript-Handbook#151]
I'm going to do the translation site content typescriptlang.org, and I wanted to have my website look the same as typescriptlang.org. Where can I get the system to build it?

**Comment by DanielRosenwasser** [comment]
We don't have the site source publicly available (and it's not clear whether it will be), but you can easily use a system like PanDoc, Kramdown (used in Jekyll), or GitBook (see work done on (#47) to publish something fairly nice.

Here's what the table-of-contents link will look like:

- Handbook
  - basic-types
  - variable-declarations
  - interfaces
  - classes
  - functions
  - generics
  - enums
  - type-inference
  - type-compatibility
  - advanced-types
  - symbols
  - iterators-and-generators
  - modules
  - namespaces
  - namespaces-and-modules
  - declaration-merging
  - writing-definition-files
  - jsx
  - decorators
  - mixins
- Project Configuration
  - tsconfig.json
  - typings-for-npm-packages
  - compiler-options
  - compiler-options-in-msbuild
  - integrations-with-build-tools

**Comment by KostyaTretyak** [comment]
Thank you @DanielRosenwasser

**Comment by DanielRosenwasser** [comment]
Keep us posted on how things work out, we understand the TypeScript community is fairly international and it'd be good to know where different translations can be found.
