### ISSUE TITLE
Fix up typescriptlang.org 'Learn' link

### ISSUE THREAD

**Issue by RyanCavanaugh** [Microsoft/TypeScript-Handbook#20]
Figure out how to merge in our .md files the way we did the CodePlex wiki content, host a 'master' MD page that links everything together, or some other way to let people read all the content in an organized fashion.

There should be some tools out there for this already.

**Comment by DanielRosenwasser** [comment]
Do we want `README.md` to contain the contents so that people landing on the page can see it? Or do we want an altogether separate `Handbook.md` to act as the master MD file?

From offhand searches, Pandoc might be the way to go.

**Comment by mhegazy** [comment]
@DanielRosenwasser let's get that done then, so that any updates we make are visible on the site. once we have something working, @jonathandturner can help you getting it on the live site.

**Comment by hristokostov** [comment]
Hi guys,

As I can see you know that the handbook section of the typescriptlang.org site doesn't show the latest version of the document (the internal module -> namespace change not mentioned). And the latest version itself doesn't mention the ES6 module loading syntax (I read about it from the language spec).  As a beginner with TypeScript (and JavaScript - that's the problem :) ) it was very hard to me (took me several hours) to realize I'm reading old documentation. I believe that the site is supposed to be the starting point for those interested in the language but outdated documentation causes a lot of confusion. I would suggest, as a first step, specifying in the document the language version it reflects and probably link to the latest version at github.

**Comment by DanielRosenwasser** [comment]
@mhegazy I think it would be appropriate to forward people to GitHub until we fix the handbook.

**Comment by mhegazy** [comment]
should be fixed now. the website has been updated see https://blogs.msdn.microsoft.com/typescript/2016/03/24/new-typescript-website/

**Comment by hristokostov** [comment]
:thumbsup:
