### ISSUE TITLE
Mix modules and namespaces 

### ISSUE THREAD

**Issue by daslicht** [Microsoft/TypeScript-Handbook#223]
Hi,
Is it possible to mix modules and namespace while still concat all namespace files ?
For example use modules on the server and concat or/and load the namespace js files in the browser?
How would you run tsc ? Separe for modules and namespaces ?
How would the tsconfig need to look like ? Please?

**Comment by mhegazy** [comment]
I would use two tsconfig.json files. one for server code, one for client code. call tsc twice, once for each config file.

**Comment by mhegazy** [comment]
StackOverflow would be a good place for such questions. this repo is mainly for the documentation bugs.

**Comment by daslicht** [comment]
Thank you for the 'kind' solution
