### ISSUE TITLE
What is the term for this ambient declaration format?

### ISSUE THREAD

**Issue by unional** [Microsoft/TypeScript-Handbook#242]
All of these are ambient module declarations:
```ts
// top-level import/export declaration format
export function foo(): void;

// Also top-level import/export declaration format?
declare namespace boo {
  export function foo(): void;
}
export = boo;

// What is the term for this format?
declare namespace boo {
  export function foo(): void;
}

declare module "boo" {
  export = boo;
}
```
The first two is how we write ambient module declaration for https://github.com/typings/typings. It is also what `tsc -d` produce if you don't perform bundling.

The last one is how people write ambient module declaration in DefinitelyTyped and subject to name conflict and resolvability issue (as described in https://github.com/typings/typings/blob/master/docs/external-modules.md)

**Comment by mhegazy** [comment]
This file is a **module**, as it has at least one top-level export or import declaration. the file is **ambient** as it does not have a body, and uses the `declare` keywrd.

```ts
export declare function foo(): void;
```

This is the same. it is a module. and it is ambient.

```ts
declare namespace boo {
  export function foo(): void;
}
export = boo;
```


This one is **not** a module. it is a **script**. it contains an **ambient module declaration**. but other than that it lives in the global declaration.

```ts
declare namespace boo {
  export function foo(): void;
}

declare module "boo" {
  export = boo;
}
```

**Comment by unional** [comment]
So can I say that it is `a script with ambient module declaration`?

**Comment by mhegazy** [comment]
yes. an "ambient module declaration" is `declare module "foo" { .. }`.
a module (regardless of being ambient or not) is something of the form `import .. ; export ..;`

**Comment by unional** [comment]
Thanks! :rose:
