### ISSUE TITLE
missing important word in explanation for Variable Declarations > Block-scoped variable capturing

### ISSUE THREAD

**Issue by tonyeung** [Microsoft/TypeScript-Handbook#245]
"When we first touched on the idea of variable capturing with var declaration, we briefly went into how variables act once captured. To give a better intuition of this, each time a scope is run, it creates an “environment” of variables. That environment and its **[i dunno what goes here]** can exist even after everything within its scope has finished executing."

I'd do a pull request but I don't know what was intended be plugged in there.

**Comment by mhegazy** [comment]
Which file is this?

**Comment by tonyeung** [comment]
https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Variable%20Declarations.md

**Comment by DanielRosenwasser** [comment]
"captured variables" probably goes there
