### ISSUE TITLE
1.8 release notes has a broken link for this-based type guards

### ISSUE THREAD

**Issue by tonyeung** [Microsoft/TypeScript-Handbook#246]
TypeScript 1.8 extends `user-defined type guard functions` to class and interface methods.
The link just points to the 1.8 release notes and appends a hash.

**Comment by mhegazy** [comment]
here is the correct link: http://www.typescriptlang.org/docs/release-notes/typescript-1.6.html#user-defined-type-guard-functions

**Comment by tonyeung** [comment]
thanks, that makes a lot more sense, now.
