### ISSUE TITLE
The website handbook pages aren't available in mobile browsers

### ISSUE THREAD

**Issue by finian** [Microsoft/TypeScript-Handbook#260]
When viewing docs pages (http://www.typescriptlang.org/docs/tutorial.html) in mobile browsers, the left nav panel is gone, just can't find any way to view the handbook pages.

**Comment by mhegazy** [comment]
looks like a duplicate of https://github.com/Microsoft/TypeScript/issues/8119

**Comment by mhegazy** [comment]
should be fixed now, can you give http://www.typescriptlang.org/docs/tutorial.html another try.

**Comment by finian** [comment]
cool. tnx.
