### ISSUE TITLE
TypeScript to generate named registers rather than anonymous registers

### ISSUE THREAD

**Issue by hanijizan** [Microsoft/TypeScript-Handbook#265]
I'm using Angular2 with SystemJS. I ran across a few issues which came down to the fact that TypeScript compiler generates anonymous registers rather than named registers:

...
System.register([...deps...], ...); //Generated by TypeScript compiler
System.register('myModule', [...deps...], ...); //How to get the compiler to do this instead?
...

This is for purpose of bundling. I like to do what Angular2 does already for my own components. Put multiple System.register calls in one minified file then import the root component.

How to accomplish this?

tsconfig:
{
  "compileOnSave": true,
  "compilerOptions": {
    "target": "es3",
    "module": "system",
    "moduleResolution": "node",
    "inlineSourceMap": true,
    "inlineSources": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "noImplicitAny": false
  }
}

**Comment by DanielRosenwasser** [comment]
This issue was moved to Microsoft/TypeScript#8385
