### ISSUE TITLE
Update Generics: It is now allowed for a type parameter to be constrained by another

### ISSUE THREAD

**Issue by spikefoo** [Microsoft/TypeScript-Handbook#267]
Section ["Using Type Parameters in Generic Constraints"](https://github.com/Microsoft/TypeScript-Handbook/blob/08696c5ddb14c2f17103eb923b425ea10a468656/pages/Generics.md#using-type-parameters-in-generic-constraints) in `Generics.md` should be updated. Constraining a type parameter using another type parameter [is allowed](https://github.com/Microsoft/TypeScript/pull/5949) as of 1.8.

**Comment by mhegazy** [comment]
A PR would appreciated.
