### ISSUE TITLE
Is there any way to bundle output file using webpack with actually libraries e.g. react?

### ISSUE THREAD

**Issue by idchlife** [Microsoft/TypeScript-Handbook#272]
I'm reading tutorial about using TS with react and seeing that there is no actually importing file inside output file. So all the purpose of using one "bundle.js" is disappearing, leaving only transpiled from TS file and two dependencies in the webpage using <script>

**Comment by mhegazy** [comment]
You could chose to bundle react with your application by not marking them as external in the webpack configuration (see https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/tutorials/React%20%26%20Webpack.md#create-a-webpack-configuration-file). This is totally your choices, and should not be impacted by using or not using TypeScript.

Please note that doing so could entail loading react multiple times for the same page, if it happen to host more than one component built this way. not bundling react allows for sharing the framework among components in the same page.

**Comment by idchlife** [comment]
@mhegazy thank you for answer! About multiple React loading. If I'm not mistaken webpack will know about React and include it once in bundle. Is there difference when using ts-loader?

**Comment by mhegazy** [comment]
@jbrantly would be a better person to answer this one.

**Comment by jbrantly** [comment]
@idchlife Using or not using ts-loader doesn't change webpack behavior in that regard. Webpack is generally good about [deduping](https://github.com/webpack/docs/wiki/optimization#deduplication). At least, I've never personally ran into a problem where React was bundled multiple times. It is theoretically possible, of course, but again using ts-loader doesn't change anything there.

**Comment by idchlife** [comment]
@jbrantly @mhegazy thank you!
