### ISSUE TITLE
[Broken links] Hyperlink on to Vim on website refers to Wiki which are now in pages/tutorials

### ISSUE THREAD

**Issue by Seikho** [Microsoft/TypeScript-Handbook#274]
The same also applies to the `Quickstart` links on the TypeScript MSDN blog referring to React+Webpack+TS and Knockout+TS.

**Comment by DanielRosenwasser** [comment]
I'm not sure what you mean regarding the Vim page - it works for me and we don't host it on the handbook.

As for the other two, thanks for the heads up! I've updated the blog post.
