### ISSUE TITLE
Writing Definition Files Example request - Properties of type Enum 

### ISSUE THREAD

**Issue by tgriley** [Microsoft/TypeScript-Handbook#282]
I've tried to find a good example of a definition that includes a property typed as an enum specific to the library and found it quite difficult. An addition to your documentation to cover this case would be fantastic.

**Comment by mhegazy** [comment]
not sure i understand the request, can you elaborate?

**Comment by tgriley** [comment]
After much digging I have been attempting to use the incorrect Type, i should have been using a string literal (http://stackoverflow.com/questions/37300738/typescript-1-8-definition-file-enum-for-magic-string-properties/).
