### ISSUE TITLE
Better webpack loader

### ISSUE THREAD

**Issue by newtack** [Microsoft/TypeScript-Handbook#292]
We are using the loader below for webpack, it may be useful to mention it in the Webpack section:

https://github.com/s-panferov/awesome-typescript-loader

**Comment by DanielRosenwasser** [comment]
When I first wrote the guide, we discussed this and @s-panferov [modestly suggested that ts-loader was a good default](https://github.com/Microsoft/TypeScript-Handbook/pull/153#issuecomment-198864057), but I agree. Recently I have seen a good number of people who've benefited from awesome-typescript-loader.

**Comment by s-panferov** [comment]
@newtack @DanielRosenwasser I still don't think that `awesome-typescript-loader` is a best default, but I don't mind about mentioning it as a possible choice.

**Comment by DanielRosenwasser** [comment]
Right, I should clarify that I'll mention that tip around that part of the tutorial or at the beginning. ts-loader is going to stay as the default.
