### ISSUE TITLE
Bad default value for the target compiler options

### ISSUE THREAD

**Issue by Gillespie59** [Microsoft/TypeScript-Handbook#295]
Right now, in this page https://www.typescriptlang.org/docs/handbook/compiler-options.html, 'ES3' is marked as the default value for the target option. That's not true anymore.

```
Specify ECMAScript target version: 'es3' (default), 'es5', or 'es6'.
```

**Comment by DanielRosenwasser** [comment]
I don't believe this is true though.

```
PS C:\Users\Daniel\TypeScript> tsc --version
Version 1.9.0-dev.20160609-1.0
PS C:\Users\Daniel\TypeScript> tsc foo.ts
foo.ts(2,9): error TS1056: Accessors are only available when targeting ECMAScript 5 and higher.
foo.ts(2,9): error TS2378: A 'get' accessor must return a value.
```

@mhegazy?

**Comment by mhegazy** [comment]
`ES3` is the default. `tsc --init` will however set you up to use `ES5`. but the default stays `ES3` if not specified.
