### ISSUE TITLE
How do i run this locally

### ISSUE THREAD

**Issue by sleekvick** [Microsoft/TypeScript-Handbook#297]
I am not sure of how to view this locally for offline use...
Please help..Thanks

**Comment by DanielRosenwasser** [comment]
Each page is in Markdown, so each page is also human-readable off the bat.

You can also view each page through a Markdown viewer (VS Code works pretty nicely). If you want to export to other formats, you can run it through Jekyll, GitBook, or Pandoc to create web pages, PDFs, etc.
