### ISSUE TITLE
Error in the documentation about callbacks definition

### ISSUE THREAD

**Issue by chmolinari** [Microsoft/TypeScript-Handbook#304]
Hi, I think I found an error at the end of this page: http://www.typescriptlang.org/docs/handbook/writing-declaration-files.html.

I was looking how to declare a callback in function and I found this:

function addLater(x: number, y: number, (sum: number) => void): void;

but it should be:

function addLater(x: number, y: number, **callback:** (sum: number) => void): void;

The name of the callback variable is missing.

**Comment by DanielRosenwasser** [comment]
Thanks for the heads up!
