### ISSUE TITLE
Module Resolution - rootDirs example

### ISSUE THREAD

**Issue by StrahilKazlachev** [Microsoft/TypeScript-Handbook#306]
Currently the [example](https://github.com/Microsoft/TypeScript-Handbook/blob/release-2.0/pages/Module%20Resolution.md) is:
```json
{
  "compilerOptions": {
    "rootDirs": [
      "src/views",
      "generated/templates"
    ]
  }
}
```
Shouldn't `"generated/templates"` be `"generated/templates/views"`?

**Comment by mhegazy** [comment]
Should be fixed in https://github.com/Microsoft/TypeScript-Handbook/commit/c3b45c7779e420662dbc647d853b2edc99454f3e
