### ISSUE TITLE
Confusion around `files` `exclude` `include` `filesGlob`

### ISSUE THREAD

**Issue by basarat** [Microsoft/TypeScript-Handbook#334]
## Docs

This section needs better docs : https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/tsconfig.json.md#details  only mentions `files` / `include`.

## Question

Also does `include` / `exclude` support globs? According to http://json.schemastore.org/tsconfig they do. I thought they were just `folder`s & `file`s. Am I wrong? 

## Suggestion 

Perhaps we can remove all `files` / `exclude` / `include` and just `filesGlob` (big breaking change I know).

Thanks :rose:

**Comment by mhegazy** [comment]
> Also does include / exclude support globs? According to http://json.schemastore.org/tsconfig they do. I thought they were just folders & files. Am I wrong?

they did. 
`include` is a new entry added in TS 2.0; both `include` and `exclude` now support glob patterns. that was merged in a few weeks back, see https://github.com/Microsoft/TypeScript/pull/5980

> This section needs better docs : https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/tsconfig.json.md#details only mentions files / include.

The updated documentation is currently in branch release-2.0 and not in master. we will be merging this into master next week. so give the updated page a look at let us know if you believe it still needs updates: https://github.com/Microsoft/TypeScript-Handbook/blob/release-2.0/pages/tsconfig.json.md

> Perhaps we can remove all files / exclude / include and just filesGlob (big breaking change I know).

I do not think we intend to support `"fileGlobs"`.

**Comment by basarat** [comment]
> I do not think we intend to support "fileGlobs".

Awesome. I realized my misunderstanding :rose:
