### ISSUE TITLE
Question about generics.md code example

### ISSUE THREAD

**Issue by zhongsp** [Microsoft/TypeScript-Handbook#343]
```ts
class BeeKeeper {
    hasMask: boolean;
}

class ZooKeeper {
    nametag: string;
}

class Animal {
    numLegs: number;
}

class Bee extends Animal {
    keeper: BeeKeeper;
}

class Lion extends Animal {
    keeper: ZooKeeper;
}

function findKeeper<A extends Animal, K> (a: {new(): A;
    prototype: {keeper: K}}): K {

    return a.prototype.keeper;
}

findKeeper(Lion).nametag;  // typechecks!
```

I'm confused with `findKeeper` function. Firstly, `findKeeper(Lion).nametag;` throws an error. Secondly, `return a.prototype.keeper;`, does `Lion.prototype` really has a `keeper`? :(
Thanks.

**Comment by RyanCavanaugh** [comment]
These examples are just meant to show type system behavior. Since none of the fields are initialized, the actual code doesn't really run.

We should change this specific example since instance fields shouldn't actually be on the prototype.

**Comment by zhongsp** [comment]
@RyanCavanaugh Thanks for ur answer!
