### ISSUE TITLE
Rename internal modules to namespaces

### ISSUE THREAD

**Issue by mhegazy** [Microsoft/TypeScript-Handbook#36]

**Comment by DanielRosenwasser** [comment]
Can I take this on? Do we want to mention the "module" keyword apart from when declaring an external module?

**Comment by danquirk** [comment]
For now I think we should keep the internal modules topic and just have one line explaining the rename and link to the new namespaces section. Likewise the namespace section should call out clearly (not some tucked away parenthetical) that namespaces were previously called internal modules. So many existing blog posts, StackOverflow answers, etc refer to internal modules we want to make sure it's easy/clear to someone coming to our docs afterwards what has happened.

**Comment by DanielRosenwasser** [comment]
Fixed by #51.
