### ISSUE TITLE
Is 'export as namespace' something new ?

### ISSUE THREAD

**Issue by BurtHarris** [Microsoft/TypeScript-Handbook#362]
The template [module.d.ts](https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/declaration%20files/templates/module.d.ts) uses a 'export as namespace' command that is flagged as an error by VsCode.  

Is this something new in TypeScript 2.0 and vsCode just hasn't caught up?

**Comment by zspitz** [comment]
It's apparently been added with 2.0 (it's on the [2.0 section of the What's New page](https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#support-for-umd-module-definitions).
[Handbook reference](https://github.com/zspitz/TypeScript-Handbook/blob/release-2.0/pages/Modules.md#umd-modules).
