### ISSUE TITLE
function return type requirement

### ISSUE THREAD

**Issue by dephiros** [Microsoft/TypeScript-Handbook#364]
These two paragraphs sounds contradictory to me. Please let me know if I just don't understand it.

The doc states that: 

> We can add types to each of the parameters and then to the function itself to add a return type. TypeScript can figure the return type out by looking at the return statements, so we can also **optionally leave this off** in many cases.

But a few paragraph later: 
> The second part is the return type. We make it clear which is the return type by using a fat arrow (=>) between the parameters and the return type. As mentioned before, **this is a required part of the function type**, so if the function doesn’t return a value, you would use void instead of leaving it off.

**Comment by dephiros** [comment]
hm looking at it a little more closely, is the second part talking about the type of the variable let myAdd: (x: number, y: number)=>number vs typing the function syntax itself function(x: number, y: number): number. From what i understand at this point, the first requires return type but the second can be inferred?

**Comment by DanielRosenwasser** [comment]
Yup - the function itself doesn't require a return type (just like in JavaScript!), but a function type literal shorthand *does* require a return type.

Basically

```ts
function foo() {
}
```

vs

```ts
var x: (param1, param2, param3) => number
```
