### ISSUE TITLE
How to resolve unresolved types in .d.ts files?

### ISSUE THREAD

**Issue by bennyn** [Microsoft/TypeScript-Handbook#374]
I am writing a TypeScript definition file for my module but [WebStorm](https://www.jetbrains.com/webstorm/) complains about unresolved types (from external modules) within my definition file. How can I resolve them? Do I need a [reference path](https://www.typescriptlang.org/docs/handbook/triple-slash-directives.html) to the external module (in my example `CBOR`)?

**Screenshot**

![unbenannt](https://cloud.githubusercontent.com/assets/469989/18135378/06d696a6-6fa2-11e6-8781-f76c07f78adc.PNG)

**Comment by mhegazy** [comment]
WebStorm uses a proprietary system to resolve TypeScript types. so i am not sure what that error message means or what is the best way to address it. https://youtrack.jetbrains.com/issues would possibly be a better place to log these issues.

**Comment by bennyn** [comment]
So by default there are no references in TypeScript definitions?

**Comment by mhegazy** [comment]
> So by default there are no references in TypeScript definitions?

I am not sure i understand the question. 

I really do not have much insight on what is going on with WebStorm to be able to help. the TS compiler comes with a set of services APIs that can be used for IDE support. these are the same ones used by Eclipse, VSCode, VS, Sublime, Emacs, and Vim. so these i know how they work. WebStorm uses their own system, so can not help much there.

**Comment by bennyn** [comment]
@mhegazy Thanks for your info! My findings are that the proprietary TypeScript support in WebStorm sometimes really behaves differently (and marks things as wrong in the IDE) than the original TypeScript compiler (`tsc`). I am having this red error in my IDE but when I run `tsc` there is no error which is good. 😃 

Thanks for your help!
