### ISSUE TITLE
TypeError: Cannot read property 'filter' of undefined

### ISSUE THREAD

**Issue by Mcburn** [Microsoft/TypeScript-Handbook#382]
Hey @ all

i had a problem with the tsconfig and pbiviz. When i use the exclude or include feature i get the Error in the headline.
But when i add the files feature i do not get the Error.

What does mean the Error? Where is filter defined? What file i miss?

**Comment by mhegazy** [comment]
This report does not provide any useful information to help diagnose the issue. If this generated in your sources, then StackOverflow would be the right place to ask this. if you believe this is a TS compiler bug, or that the crash is happening in the TS compiler sources, please file an issue on https://github.com/Microsoft/TypeScript, provide information on the version, what you are doing, and what is going wrong. also include a code sample, and/or a sample of your tsconfig.json.
