### ISSUE TITLE
mistakes in webpack configuration file

### ISSUE THREAD

**Issue by marzelin** [Microsoft/TypeScript-Handbook#403]
Example webpack configuration file in *tutorials/React & Webpack.md* contains mistakes.
According to [webpack documentation](http://webpack.github.io/docs/configuration.html#output-filename) `output.filename` is used solely for naming the individual files. The `output.path` option (which is required) determines the location on disk where the files are written to.

So,

    output: {
        filename: "./dist/bundle.js",
    },

Should be changed to:

    output: {
        filename: "bundle.js",
        path: "./dist"
    },

**Comment by marzelin** [comment]
Fixed: #405

**Comment by DanielRosenwasser** [comment]
Thanks!
