### ISSUE TITLE
Possible typo - source type or target type?

### ISSUE THREAD

**Issue by ahmadferdous** [Microsoft/TypeScript-Handbook#419]
Hi,

I'm new to TypeScript. I have found this handbook amazing. It's concise and to the point. Thank you all the contributors!

I found the following excerpt from the chapter "Type Compatibility", section ["Optional Parameters and Rest Parameters"](https://github.com/Microsoft/TypeScript-Handbook/blob/a94e6454989c15a0aea2ea017aef9b14f9affa49/pages/Type%20Compatibility.md#optional-parameters-and-rest-parameters) confusing.

_When comparing functions for compatibility, optional and required parameters are interchangeable. Extra optional parameters of the source type are not an error, and optional parameters of the target type without corresponding parameters in the **target type** are not an error._

Is the "target type" in bold actually a typo? Was it supposed to be "source type"?

Thanks in advance.

**Comment by oboukli** [comment]
This is fixed
