### ISSUE TITLE
Broken link for tsconfig

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript-Handbook#431]
https://twitter.com/argo_49/status/795010809910788096

Link for tsconfig.json on: https://www.typescriptlang.org/docs/handbook/react-&-webpack.html

Points to: https://www.typescriptlang.org/docs/tsconfig-json.html
Should be: https://www.typescriptlang.org/docs/handbook/tsconfig-json.html

**Comment by mhegazy** [comment]
We change the directory structure when we publish to the site, so we should stop doing that.

**Comment by andy-ms** [comment]
There's also a broken link in: http://www.typescriptlang.org/docs/handbook/compiler-options.html
The links for `See @types, -typeRoots and -types` go to: http://www.typescriptlang.org/docs/handbook/tsconfig.json.md#types-typeroots-and-types
They should go to: http://www.typescriptlang.org/docs/handbook/tsconfig-json.html#types-typeroots-and-types

**Comment by mhegazy** [comment]
Fixed by https://github.com/Microsoft/TypeScript-Handbook/pull/474
