### ISSUE TITLE
Deprecate enum

### ISSUE THREAD

**Issue by mkusher** [Microsoft/TypeScript-Handbook#476]
Should enums be marked as deprecated or not recommended to use?

**Comment by mhegazy** [comment]
Enums are not deprecated and there are no planes to depreciate them either.

**Comment by mkusher** [comment]
@mhegazy maybe some updates to the docs, since they are not working properly?

**Comment by DanielRosenwasser** [comment]
Working properly in what sense?

**Comment by mkusher** [comment]
@DanielRosenwasser https://github.com/vkurchatkin/typescript-vs-flow/blob/master/ts/4.ts

**Comment by mhegazy** [comment]
This is working as intended to support flag enums.. consider:

```ts
enum flags {
    red = 0x0001
    round = 0x0010;
    hasSeeds = 0x0100;
}

declare function isValid(flags: Flags): booelan;

isValid(/*tomato*/ 0x0111) // true;
```

So if all what you want is a set of literals, do not use enums. use union types.. e.g.
```ts
export function test(v: 1 | 2 | 3 | 4) {
}

test(100); // Error
```
you could give them symnbolic names if you want, and still use union types:

```ts
type Up = 1;
type Down= 2;
type Left= 3;
type Righ= 4;

export function test(v: Up | Down | Left | Righ) {
}
```

**Comment by vkurchatkin** [comment]
> This is working as intended to support flag enums

It makes enums essentially this:

```js
type  Flags = number;
const red = 0x0001
const round = 0x0010;
const hasSeeds = 0x0100;
```

**Comment by mhegazy** [comment]
Enum has two uses, one as a collection of constants, as you point out, and the other as a type. Number is allowed to allow for flag enums, and to allow for numeric manipulations on enum values. 

If you need a closed set of constants, use literal types.

**Comment by lifeiscontent** [comment]
not being able to have enums as static properties on a class is annoying.

e.g.

```ts
class Drink {
  static enum Size {Small, Medium, Large}
}
```
