### ISSUE TITLE
sumMatrix example does not demo let shadowing issue

### ISSUE THREAD

**Issue by atifaziz** [Microsoft/TypeScript-Handbook#480]
The [Re-declarations and Shadowing](https://github.com/Microsoft/TypeScript-Handbook/blob/v2.0/pages/Variable%20Declarations.md#re-declarations-and-shadowing) section of the [Variable Declaration](https://github.com/Microsoft/TypeScript-Handbook/blob/v2.0/pages/Variable%20Declarations.md) page [describes a problem with `let` and shadowing](https://github.com/Microsoft/TypeScript-Handbook/blame/v2.0/pages/Variable%20Declarations.md#L310-L328), and an example to demo the issue:

> The act of introducing a new name in a more nested scope is called *shadowing*.
It is a bit of a double-edged sword in that it can introduce certain bugs on its own in the event of accidental shadowing, while also preventing certain bugs.
For instance, imagine we had written our earlier `sumMatrix` function using `let` variables.

```ts
function sumMatrix(matrix: number[][]) {
    let sum = 0;
    for (let i = 0; i < matrix.length; i++) {
        var currentRow = matrix[i];
        for (let i = 0; i < currentRow.length; i++) {
            sum += currentRow[i];
        }
    }

    return sum;
}
```

> This version of the loop will actually perform the summation correctly because the inner loop's `i` shadows `i` from the outer loop.

However, the example _doesn't_ exhibit the issue. If you paste it into the [Playground](https://www.typescriptlang.org/play/index.html), the compiled JavaScript code appears as:

```js
function sumMatrix(matrix) {
    var sum = 0;
    for (var i = 0; i < matrix.length; i++) {
        var currentRow = matrix[i];
        for (var i_1 = 0; i_1 < currentRow.length; i_1++) {
            sum += currentRow[i_1];
        }
    }
    return sum;
}
```

Note that the inner loop variable is renamed to `i_1` whereas the outer one remains as `i` and each is updated independently. If you run [the example in the Playground][eg] then it correctly displays the expected result of 21 given a matrix of `[[1, 2, 3], [4, 5, 6]]`. Changing the inner loop variable to, say `j`, has no effect and produces the same result. It leaves the reader misinformed or confused if they are trying to observe the effects by running the example. Unless I'm missing something, the example should be removed.

The only case of shadowing with `let` that I'm aware of is the one [quoted on MDN](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Statements/let#Temporal_dead_zone_and_errors_with_let):

> Using `let` with a variable name that is the same as a parameter passed to a function will result in error inside a `for` loop.

```js
function go(n){
  for (let n of n.a) { // TypeError: n is undefined
    console.log(n);
  }
}

go({a:[1,2,3]});
```

However, this is an issue of _shadowing a function parameter_ with a looping variable scoped to a `for` loop via a `let`.

[eg]: https://www.typescriptlang.org/play/index.html#src=function%20sumMatrix(matrix%3A%20number%5B%5D%5B%5D)%20%7B%0D%0A%20%20%20%20let%20sum%20%3D%200%3B%0D%0A%20%20%20%20for%20(let%20i%20%3D%200%3B%20i%20%3C%20matrix.length%3B%20i%2B%2B)%20%7B%0D%0A%20%20%20%20%20%20%20%20var%20currentRow%20%3D%20matrix%5Bi%5D%3B%0D%0A%20%20%20%20%20%20%20%20for%20(let%20i%20%3D%200%3B%20i%20%3C%20currentRow.length%3B%20i%2B%2B)%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20sum%20%2B%3D%20currentRow%5Bi%5D%3B%0D%0A%20%20%20%20%20%20%20%20%7D%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20return%20sum%3B%0D%0A%7D%0D%0A%0D%0Aalert(sumMatrix(%5B%5B1%2C%202%2C%203%5D%2C%20%5B4%2C%205%2C%206%5D%5D))%3B%0D%0A

**Comment by mhegazy** [comment]
I am not sure i understand the issue here. [variable shadowing](https://en.wikipedia.org/wiki/Variable_shadowing) is accurately described in this handbook article as it is in the Wikipedia article. shadowing a `let` is not illegal, it is legal and behaves as intended. it is not a problem it is a feature of `let` declarations. with `var` you would have had to name your inner loop variable `j` to avoid collision with `i` from out loop, with `let` you do not get this, the scopes of the variables are the blocks, and inner ones shadow outer ones.

When you compile to ES5, `let` and `const` are not available, only `var`s which are function scoped. The TS compiler transforms your `let` and `const` declarations to `var` in a way that honors their semantics, and thus renaming the `i` into `i_1`.

**Comment by atifaziz** [comment]
@mhegazy I think the passage just read confusing at the time when I reported this. Going back and reading it again (though I'm sure I did too back then), I see that there is no issue here.
