### ISSUE TITLE
@required is referenced by not shown

### ISSUE THREAD

**Issue by appsforartists** [Microsoft/TypeScript-Handbook#481]
In the [Decorators](http://www.typescriptlang.org/docs/handbook/decorators.html) section, `@required` is mentioned:

> The following is an example of a parameter decorator (`@required`) applied to parameter of a member of the `Greeter` class:

but the code snippet doesn't include `@required`:

```typescript
class Greeter {
    greeting: string;

    constructor(message: string) {
        this.greeting = message;
    }

    @validate
    greet(@required name: string) {
        return "Hello " + name + ", " + this.greeting;
    }
}
```

From the context (parameter decorators), I'm guessing the `@required` should be on `greeting`.

**Comment by mhegazy** [comment]
it would use Reflect.metadata, then check it in validate that it is not `undefined`. Feel free to send a PR adding the definition.

**Comment by appsforartists** [comment]
I see it now - it was in the arguments for `greet`.
