### ISSUE TITLE
Clarify capabilities of the rootDirs option

### ISSUE THREAD

**Issue by aluanhaddad** [Microsoft/TypeScript-Handbook#483]
`rootDirs` is a really powerful feature. I love it. It allows some very precise runtime behavior to be modeled but I think this could be more discoverable.
Recently I attempted to model [JSPM's conditional substitution](http://jspm.io/0.17-beta-guide/conditional-substitution.html) feature.

Essentially this involves an import such as
```ts
import salutation from './#{lang}/text';
```
The directory layout I used was
**src/**
--- **main.tsx**
--- **en/**
------- **text.tsx**
---**zh/**
------- **text.tsx**

While I could have used an ambient external module declaration, I figured there would be a way to get TypeScript to resolve one of the files containing the conditional import by substituting either **zh** or **en** statically and resolving that path.
There is a way but it is not at all clear that it will work. I essentially stumbled on it by accident.
```js
{
  "compilerOptions": {
    "module": "system",        
    "target": "es2015",
    "rootDirs": [
      // only one of zh or en is actually needed
      "src/zh",
      "src/en",
      "src/#{lang}"
    ]
  }
}
```
It would be great if the documentation were expanded to explain this as it seems non-obvious that the non-existent directory **src/#{lang}** would even be a valid entry. The configuration above was the last one I tried and I did not expect it to work.

**Comment by mhegazy** [comment]
A PR would be appreciated.

**Comment by aluanhaddad** [comment]
@mhegazy Great. I will try to put a PR together this weekend.

**Comment by aluanhaddad** [comment]
Created https://github.com/Microsoft/TypeScript-Handbook/pull/539
