### ISSUE TITLE
"DefinitelyTyped repo external package list" link on /declaration-files/publishing page is 404 Not Found.

### ISSUE THREAD

**Issue by tomof** [Microsoft/TypeScript-Handbook#490]
### page (declaration-files/publishing)
https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/declaration%20files/Publishing.md#publicize-your-declaration-file

### link (404 Not Found)
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/types-2.0/notNeededPackages.json

The link "DefinitelyTyped repo external package list" on /declaration-files/publishing page is 404 Not Found. Does anyone know where the page moved?

**Comment by mhegazy** [comment]
I have removed this section altogather (https://github.com/Microsoft/TypeScript-Handbook/commit/17098fde05099b0d70cc6be0f0420cc10ea0de38).

The file is at: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/notNeededPackages.json
The file should only be edited if your package declaration was on Definitlly Typed, then you decided to include it in your npm package.

For search, we have a crawling job that looks at all npm packages and updates the search index for ones that have `types`\`typings` in their `package.json`

**Comment by tomof** [comment]
All right.
Thank you for your reply and commitment.
