### ISSUE TITLE
Document type guards and determining runtime type information

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript-Handbook#52]
Somewhat related is @drudru's issue filed here: https://github.com/Microsoft/TypeScript/issues/3660.

**Comment by mhegazy** [comment]
please see my comment: https://github.com/Microsoft/TypeScript/issues/3660#issuecomment-116782393

use function.name if available or use a pollyfill for it.

**Comment by DanielRosenwasser** [comment]
Fixed by #74, though the second half of this isn't covered.

**Comment by DanielRosenwasser** [comment]
Actually, since #35 covers type guards, maybe we should keep this open.

**Comment by mhegazy** [comment]
this should be fixed now.
