### ISSUE TITLE
'Publishing' page doesn't tell users to use the --declaration flag

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript-Handbook#527]

**Comment by mhegazy** [comment]
A PR would be appreciated

**Comment by Vilvalas** [comment]
The issue seems to have been fixed by [this commit](https://github.com/Microsoft/TypeScript-Handbook/commit/884e4e80f0868a2057234796f6a2076e27582d8d#diff-838496c430211cc74d37c3d32399275f) and should be closed.

However I still found some typos, which I corrected in my PR.
