### ISSUE TITLE
All links included spaces are broken

### ISSUE THREAD

**Issue by falsandtru** [microsoft/TypeScript-Handbook#533]
Probably because of the breaking changes of gfm.

e.g. https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Compiler%20Options.md

**Comment by DanielRosenwasser** [comment]
To be clear, you mean on GitHub, right?

**Comment by falsandtru** [comment]
Yes, I said about GitHub (GitHub Flavored Markdown).
The gfm spec says The destination cannot contain spaces or line breaks, even if enclosed in pointy brackets: https://github.github.com/gfm/#example-472

**Comment by DanielRosenwasser** [comment]
Yeah, I figured. *sigh* we had some assumptions about how things currently worked. I guess I'll get rid of [this too](https://github.com/DanielRosenwasser/JekyllMarkdownLinkConverter).
