### ISSUE TITLE
Intersection Types example fails to compile

### ISSUE THREAD

**Issue by icepeng** [Microsoft/TypeScript-Handbook#548]
https://www.typescriptlang.org/docs/handbook/advanced-types.html
With TS 2.2, example produce following errors
```
function extend<T, U>(first: T, second: U): T & U {
    let result = <T & U>{};
    for (let id in first) {
        (<any>result)[id] = (<any>first)[id];
    }
    for (let id in second) {
        if (!result.hasOwnProperty(id)) {
            (<any>result)[id] = (<any>second)[id];
        }
    }
    return result;
}
```
The `log` method is translated as a closure, so it can not be used as a property of `second`.

Suggested Change:
```
interface Loggable {
    log: () => void;
}
class ConsoleLogger implements Loggable {
    log = () => {
        console.log('asdf');
    }
}
```

**Comment by mhegazy** [comment]
i do not see any errors in the [playground](http://www.typescriptlang.org/play/index.html#src=function%20extend%3CT%2C%20U%3E(first%3A%20T%2C%20second%3A%20U)%3A%20T%20%26%20U%20%7B%0D%0A%20%20%20%20let%20result%20%3D%20%3CT%20%26%20U%3E%7B%7D%3B%0D%0A%20%20%20%20for%20(let%20id%20in%20first)%20%7B%0D%0A%20%20%20%20%20%20%20%20(%3Cany%3Eresult)%5Bid%5D%20%3D%20(%3Cany%3Efirst)%5Bid%5D%3B%0D%0A%20%20%20%20%7D%0D%0A%20%20%20%20for%20(let%20id%20in%20second)%20%7B%0D%0A%20%20%20%20%20%20%20%20if%20(!result.hasOwnProperty(id))%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20(%3Cany%3Eresult)%5Bid%5D%20%3D%20(%3Cany%3Esecond)%5Bid%5D%3B%0D%0A%20%20%20%20%20%20%20%20%7D%0D%0A%20%20%20%20%7D%0D%0A%20%20%20%20return%20result%3B%0D%0A%7D). can you elaborate?

**Comment by icepeng** [comment]
Typescript playground is on TS 2.3.3 now. This issue was opened when TS version was 2.2.x.
