### ISSUE TITLE
Documentation about using a class as an interface

### ISSUE THREAD

**Issue by raxkaynan** [microsoft/TypeScript-Handbook#594]
Under this section: [Using a class as an interface](https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Classes.md#using-a-class-as-an-interface), the example shown doesn't demonstrate a class as an interface. A class as an interface should be _implemented_ by another class using the `implements` keyword.

**Comment by mhegazy** [comment]
> A class as an interface should be implemented by another class using the implements keyword.

not necessary. an interface declares a type, a class declares a type and a constructor function. this part stresses the type that a class declares.

**Comment by raxkaynan** [comment]
I opened this issue almost exactly 2 years ago, and I was quite new to TypeScript back then. I have to agree to @mhegazy 's explanation. So I'm closing this issue now.
