### ISSUE TITLE
Font size on an embedded list on module-resolution.md being rendered oddly

### ISSUE THREAD

**Issue by brettcannon** [Microsoft/TypeScript-Handbook#607]
If you look at http://www.typescriptlang.org/docs/handbook/module-resolution.html you will notice that the embedded `ol` list in the path mapping subsection is overly large (e.g. search for "pattern ‘*’ is matched and wildcard captures the whole module name"). The issue seems to be a CSS rule that sets `ol li` to `1.6em` which automatically _increases_ the font by 60% over the baseline size of the rest of the page. This unfortunately "washes out" the top-level bullet points as the sub-list is `1.6em` of the parent list.

**Comment by ZhangYiJiang** [comment]
Duplicated of https://github.com/Microsoft/TypeScript-Handbook/issues/441
