### ISSUE TITLE
Docs homepage links to old release notes

### ISSUE THREAD

**Issue by laughinghan** [Microsoft/TypeScript-Handbook#629]
On [the docs homepage](https://www.typescriptlang.org/docs/home.html), the link `latest TypeScript release` links to 2.3 rather than 2.4:

<img width="441" alt="screen shot 2017-07-25 at 2 51 48 pm" src="https://user-images.githubusercontent.com/225809/28595464-d6df92aa-7148-11e7-8586-a294d03199e3.png">

**Comment by mhegazy** [comment]
@DanielRosenwasser looks like a bug in the site, how do you want to track it.

**Comment by corydeppen** [comment]
I'm surprised a few releases have gone by without this being updated.

**Comment by mhegazy** [comment]
Should be updated now.
