### ISSUE TITLE
[Documentation] hybrid types example has compilation error

### ISSUE THREAD

**Issue by eriknyk** [Microsoft/TypeScript-Handbook#641]
Hy I was trying to use the example as it described in the section `Hybrid Types`
https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Interfaces.md#hybrid-types

It cause an Error: `Type '() => void'  cannot converted to to type 'Counter'`

```
interface Counter {
    (start: number): string;
    interval: number;
    reset(): void;
}

function getCounter(): Counter {
    let counter = <Counter>function (start: number) { };  // <--- ERROR HERE 
    counter.interval = 123;
    counter.reset = function () { };
    return counter;
}

let c = getCounter();
c(10);
c.reset();
c.interval = 5.0;
```

I solve that changing 

    let counter = <Counter>function (start: number) { };  // Cause error

by

    let counter = <Counter> { };  // works

I wish to know if this is because a version that I'm using, or what happened?

dev info:

```
ts-loader: Using typescript@2.4.1 and /Users/erik/Projects/tsconfig.json
```

Best Regards.

**Comment by mhegazy** [comment]
A PR would be appreciated.

**Comment by eriknyk** [comment]
no sorry, example it works,
the problem exists when I have same implementation but without a constructor

![image](https://user-images.githubusercontent.com/205721/29850798-cc739046-8cf5-11e7-8e9f-d585a7aa30d9.png)

but when the implementation has a constructor it works

![image](https://user-images.githubusercontent.com/205721/29850819-e8c89eb2-8cf5-11e7-9d7e-cfbc6980e99c.png)

...

a workaround to solve  the 1st case of implementation is changing `function(){}` by `{}`
so this solve that case:

![image](https://user-images.githubusercontent.com/205721/29850852-25b6855a-8cf6-11e7-805b-1b43883ac9c9.png)

Best Regards.
