### ISSUE TITLE
Document `ThisType<T>`

### ISSUE THREAD

**Issue by mattmccutchen** [Microsoft/TypeScript-Handbook#649]
Document the `ThisType<T>` marker interface that can be included (via intersection) in the contextual type of an object literal to set the type of `this` for methods defined in the object literal.  It doesn't seem to be documented anywhere but the [pull request description](https://github.com/Microsoft/TypeScript/pull/14141).

I'll propose text if I have a chance (not right now).

**Comment by mweststrate** [comment]
I love this feature. Deserves some documentation indeed :)
