### ISSUE TITLE
Error in documentation about type inference

### ISSUE THREAD

**Issue by jrmoller** [Microsoft/TypeScript-Handbook#652]
See https://stackoverflow.com/questions/46474093/typescript-error-in-documentation-about-type-inference

**Comment by Steve-Fenton** [comment]
Just to expand this ticket - the MouseEvent does seem to have a button property (number), so has the documentation been outdated by an update to lib.d.ts... perhaps we could show contextual typing with:

```
// mouseEvent is a MouseEvent
window.onmousedown = function (mouseEvent) {
    console.log(mouseEvent.button);
};

// mouseEvent is a UIEvent
window.onscroll = function(mouseEvent) {
    console.log(mouseEvent.button);  //<- Error
};
```

**Comment by Hobinx** [comment]
The link @jrmoller is removed. I encountered this error today, I describe the error in documentation here:
```
window.onmousedown = function(mouseEvent) {
    console.log(mouseEvent.button);  //<- Error
};
```
Actually, these is no error at all, I think the example is like @Steve-Fenton said, outdated. This confuse people.

**Comment by arthanzel** [comment]
I've just encountered this issue while learning TS. Since I haven't seen any further work on this, I've submitted PR #786 to fix this issue.
