### ISSUE TITLE
React & Webpack doc missing entry point explanation

### ISSUE THREAD

**Issue by colinangusmackay** [Microsoft/TypeScript-Handbook#668]
This file:
https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/tutorials/React%20%26%20Webpack.md

States: 

> You'll be given a series of prompts. You can use the defaults except for your entry point. You can always go back and change these in the package.json file that's been generated for you.

But nowhere does it say what the entry point should be set to given it isn't the default value suggested by the tool.

**Comment by DanielRosenwasser** [comment]
It's not even used, so I'll remove it entirely in #673.
