### ISSUE TITLE
Sugestion - Compiler option

### ISSUE THREAD

**Issue by iburman** [Microsoft/TypeScript-Handbook#686]
I just came across a bug in my code, that I would expect to be caught by the compiler. The code is basically this:
`
{
    let a = new Something(parameters);
    ... some code..
    {
         let a = new Something(parameters);
    }

}
`
the "let a =.." inside the inner block was actually a mistake, the real intention was to use the same variable defined in the outer block.
While debugging the issue I found out the Typescript compiled the inner block as:
   var a_1 = new Something(parameters);
so it created a new variable by appending a "_1".
While I just figured out that this is by design, I believe that many people, me included, would prefer this to be reported as a bug, like the C# compiler, that doesn't allow you to have a variable in the inner block redefined with the same name of an existing variable from the outer block.
Is it possible to include a compiler option where doing this would be considered an error?

Thanks

**Comment by mhegazy** [comment]
Consider using [tslint no-shadowed-variable rule](https://palantir.github.io/tslint/rules/no-shadowed-variable/)

**Comment by iburman** [comment]
Thanks a lot mhegazy. The TSlint rule you suggested does what I was looking for.
