### ISSUE TITLE
Unclear Interface naming Convention , how to distinguish from Class Name?

### ISSUE THREAD

**Issue by hen42** [Microsoft/TypeScript-Handbook#690]
Hi Guys,
in C# we often prefix an interface name with an "I" like IMailService. 
In TypeScript the guidelines says don't useprefix "I".

Are there any recommendations how to distinguish the interface name from the class name in TypeScript ?
Should I name the interface  MailServiceInterface, MailServiceType or MailServiceDefinition ? or something else.?

Thanks and

Best Regards

**Comment by mhegazy** [comment]
TS does not have specific coding guidelines. you are free to use whatever coding style you like. for the TS code base, we chose not to use `I`'s.
