### ISSUE TITLE
question about Virtual Directories with rootDirs

### ISSUE THREAD

**Issue by lzl124631x** [Microsoft/TypeScript-Handbook#699]
In the [handbook](https://www.typescriptlang.org/docs/handbook/module-resolution.html), section Virtual Directories with rootDirs, the first example shows that you can imports modules from different source folder by merging different `rootDirs` as one.
```
// File Structure
 src
 └── views
     └── view1.ts (imports './template1')
     └── view2.ts

 generated
 └── templates
         └── views
             └── template1.ts (imports './view2')
```
```
// Setting
{
  "compilerOptions": {
    "rootDirs": [
      "src/views",
      "generated/templates/views"
    ]
  }
}
```
Notice that you can omit the paths listed in `rootDir` when importing a module.

What I don't under stand is the second example.

```
{
  "compilerOptions": {
    "rootDirs": [
      "src/zh",
      "src/de",
      "src/#{locale}"
    ]
  }
}
```
> "The compiler will now resolve import messages from `'./#{locale}/messages'` to import messages from `'./zh/messages'` for tooling purposes".

* Why?
* Is `#{locale}` replaced as `zh` in building process?
* Why are we using relative path in `./#{locale}/messages`? What if the importing file is at `src/folderA/`?
* Given that `src/zh` is merged as a rootDir, shouldn't it be `/messages` to import?

The example didn't show the file structure so I'm confused. Looking forward to response. Thanks!

**Comment by mhegazy** [comment]
this is useful if you have a post build step that will copy files from multiple source directories to a single output directory. for instance all generated outputs form `./src/*` and `./generated/*` will be copies to `./output` after the build is completed. the rootDirs tell the compiler about this merge. 

Please note that the compiler is not moving anything. so if you do not have that post-build step that copies things for you, outputs will be in the wrong place.
