### ISSUE TITLE
Webpack 4 compat - React & Webpack.md 

### ISSUE THREAD

**Issue by technion** [Microsoft/TypeScript-Handbook#727]
Hi,

I'm just wondering if the instructions in this file had been tested with Webpack 4.

I've tried upgrading to this new release, and although I can get everything to compile and run, I can't work out if the issue is:

- The process documented
- Webpack 4 in general
- source-map-loader

Any assistance appreciated. Obviously, my apologies if this issue clearly exists elsewhere.

**Comment by DanielRosenwasser** [comment]
I haven't tried it out yet, but what issues have you run into?

**Comment by technion** [comment]
Issue I'm hitting is that it "works" but the produced source map contains javascript, and not the original Typescript.

**Comment by technion** [comment]
I'm going to write this off as one of those things. I upgraded a separate project and everything worked. So, webpack 4 compat confirmed I guess.
