### ISSUE TITLE
Destructing section is not pragmatic

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/TypeScript-Handbook#729]
From @rauschma:

Destructuring in function declarations seems wrong: https://t.co/Qg7HR4NQgx

You’d never do:
f({ a, b } = { a: "", b: 0 })

Instead:
f({ a="", b=0 } = {})
You can even omit the ={} at the end in many cases.

It’s a shame that the manual warns about this pattern which is really useful.

**Comment by rauschma** [comment]
To elaborate:

* With the first definition, you can only omit the complete object.
* With the second definition, you can omit the complete object, both `a` and `b` or either `a` and `b` and the defaults always work.

**Comment by Vimal-Raghubir** [comment]
Is it possible for me to work on this issue and submit a PR?
