### ISSUE TITLE
ReturnType<T> example in Release Notes for TypeScript 2.8 is different from lib.d.ts

### ISSUE THREAD

**Issue by lambdageek** [Microsoft/TypeScript-Handbook#741]
In `lib.d.ts`, `ReturnType<T>` is defined here
https://github.com/Microsoft/TypeScript/blob/release-2.8/lib/lib.d.ts#L1386

> ```typescript
> type ReturnType<T extends (...args: any[]) => any> = T extends (...args: any[]) => infer R ? R : any;
> ```

Note that in the "else" case, the type is `any`.  (So `ReturnType<number>` is `any`, for example).

This is different from every single example definition of `ReturnType<T>` in the release notes:

> ```typescript
> type ReturnType<T> = T extends (...args: any[]) => infer R ? R : T;
> ```

(`ReturnType<number>` is `number`)

> ```typescript
> type AnyFunction = (...args: any[]) => any;
> type ReturnType<T extends AnyFunction> = T extends (...args: any[]) => infer R ? R : never;
> ```

(`ReturnType<number>` is `never`)

The handbook and the actual implementation should be rationalized.  (I think `never` is a more sensible result, than `any`, but that should be a separate issue...).

Note that for other types where the handbook presents a notional definition, there's a disclaimer that
the example is not meant to be taken literally:

> Note: The `Exclude` type is a proper implementation of the `Diff` type suggested here. We’ve used the
> name `Exclude` to avoid breaking existing code that defines a `Diff`, plus we feel that name better
> conveys the semantics of the type. We did not include the `Omit<T, K>` type because it is trivially
> written as `Pick<T, Exclude<keyof T, K>>`.

Now, aside from this note mentioning types that are not anywhere in the release notes, the same sort of thing should be said about `ReturnType` and other types that are only for illustration.

**Comment by mhegazy** [comment]
> Note: The Exclude type is a proper implementation of the Diff type **suggested [here](https://github.com/Microsoft/TypeScript/issues/12215#issuecomment-307871458)**. We've used the name Exclude to avoid breaking existing code that defines a Diff, plus we feel that name better conveys the semantics of the type. We did not include the Omit<T, K> type because it is trivially written as Pick<T, Exclude<keyof T, K>>.

If you click on the link you will see where the types are declared. The types were never in the standard library but were in wide circulation outside it. this is what the note refers to.

**Comment by lambdageek** [comment]
I don't think 24e04d7 is a correct fix.

You made both of the handbook definitions the same.

But they are still different from what's in `lib.d.ts`.   You should either make the definition in the handbook exactly the same as what's in `lib.d.ts` or else add a disclaimer in the handbook that the definition is not correct.
