### ISSUE TITLE
Documentation for Conditional Types?

### ISSUE THREAD

**Issue by dallonf** [Microsoft/TypeScript-Handbook#747]
It doesn't seem that Conditional Types are described in the [TypeScript Handbook](https://www.typescriptlang.org/docs/index.html). I would expect to find them under [Advanced Types](https://www.typescriptlang.org/docs/handbook/advanced-types.html) (or on their own page) - no other page seems to fit - but a quick search on that page for "conditional", "extends", "?", and similar keywords yields nothing relevant.

It seems that they are currently only described in the [TypeScript 2.8 Release Notes](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-8.html), which is kind of a bummer if you haven't memorized the exact version that added the feature :)

Fortunately, the Release Notes are pretty descriptive, so they could probably be copied from there into Advanced Types with minimal edits. I could take a stab at doing that in a PR - just wanted to check first that there's no deeper reason why they haven't been documented or if it actually is somewhere else that I didn't think to look.

**Comment by marcind** [comment]
Looking for these docs as well. I would suggest that it's also high time to break up the Advanced Types section into multiple pages.

**Comment by DeTeam** [comment]
@mhegazy do you think, it's something worth acting? 🙂

It's been a while since conditional types + some other features were released. Updating docs would be a good thing to do.

**Comment by mhegazy** [comment]
We would accept a PR adding a section on Conditional Types. consider using the content in https://blogs.msdn.microsoft.com/typescript/2018/03/27/announcing-typescript-2-8/

You can also look at https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/release%20notes/TypeScript%202.8.md#conditional-types as a reference.

**Comment by nealeu** [comment]
I'm using conditional types to help with functions that return null if and only if the arg is null, such that it resolves a lot of strictNullCheck scenarios.

For example:
```
function parseNullable<T extends string|null>(str: T): maybeNull<T, number> {
    return str && parseInt(str as string) as maybeNull<T, number>;
}
 */
export type maybeNull<T, RES> = T extends null ? null : RES;
```

Is this worth adding to the docs as an example?  

It's a bit strained with the casts, but works well for library methods, avoiding false negatives.
