### ISSUE TITLE
Documentation for getting around Excess Property Checks is Wrong(?old)

### ISSUE THREAD

**Issue by mani-mishra** [Microsoft/TypeScript-Handbook#762]
In interfaces chapter, at https://github.com/mani-mishra/TypeScript-Handbook/blob/master/pages/Interfaces.md#excess-property-checks
we have following,

> One final way to get around these checks, which might be a bit surprising, is to assign the object to another variable: Since squareOptions won't undergo excess property checks, the compiler won't give you an error.
```ts
let squareOptions = { colour: "red", width: 100 };
let mySquare = createSquare(squareOptions);
```

But when I tried the same example in [TS playground](https://www.typescriptlang.org/play/index.html#src=interface%20SquareConfig%20%7B%0D%0A%20%20%20%20color%3F%3A%20string%3B%0D%0A%20%20%20%20width%3F%3A%20number%3B%0D%0A%7D%0D%0A%0D%0Afunction%20createSquare(config%3A%20SquareConfig)%3A%20%7B%20color%3A%20string%3B%20area%3A%20number%20%7D%20%7B%0D%0A%20%20%20%20let%20newSquare%20%3D%20%7Bcolor%3A%20%22white%22%2C%20area%3A%20100%7D%3B%0D%0A%20%20%20%20if%20(config.color)%20%7B%0D%0A%20%20%20%20%20%20%20%20newSquare.color%20%3D%20config.color%3B%0D%0A%20%20%20%20%7D%0D%0A%20%20%20%20if%20(config.width)%20%7B%0D%0A%20%20%20%20%20%20%20%20newSquare.area%20%3D%20config.width%20*%20config.width%3B%0D%0A%20%20%20%20%7D%0D%0A%20%20%20%20return%20newSquare%3B%0D%0A%7D%0D%0A%0D%0A%2F%2F%20This%20works%0D%0Alet%20mySquare%20%3D%20createSquare(%7B%20color%3A%20%22black%22%20%7D)%3B%0D%0A%0D%0A%2F%2F%20This%20is%20an%20error%20(which%20is%20what%20we%20want%2C%20%0D%0A%2F%2F%20to%20have%20strict%20properties%20check)%0D%0Alet%20mySquare1%20%3D%20createSquare(%7Bcolour%3A%20%22black%22%7D)%3B%0D%0A%0D%0A%0D%0A%2F%2F%20But%20one%20of%20the%20very%20common%20pattern%20of%20passing%20values%20circumvents%20that%20(according%20to%20docs)%0D%0Alet%20sqOptions%20%3D%20%7B%20colour%3A%20%22black%22%20%7D%3B%0D%0A%0D%0A%2F%2F%20But%20I%20see%20an%20error%20in%20playground%20(So%20docs%20should%20be%20updated)%0D%0Alet%20mySquare2%20%3D%20createSquare(sqOptions)%3B), I do get the squiggly red marker and tooltip  that even the above workaround is wrong(which is correct, as this is very common pattern).

So, maybe the docs need updating?

I'm happy to raise a PR if required.

**Comment by DanielRosenwasser** [comment]
We need to document weak type checking, which is a check for when an all-optional interface rejects anything that doesn't have any properties in common.

**Comment by bhagatparwinder** [comment]
Check the code sample and added an exception to excess property check workaround 🙏
