### ISSUE TITLE
Unnecessary Savagery

### ISSUE THREAD

**Issue by ToJen** [Microsoft/TypeScript-Handbook#793]
This line right here mate, is not necessary in a product's official documentation. :fire: 

> However, combining the two naively would let you to shoot yourself in the foot the same way you might in JavaScript.

(line 149)
https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Interfaces.md

**Comment by mhegazy** [comment]
A PR to update the referenced phrase would be appreciated.

**Comment by ToJen** [comment]
nvm lol, keeps readers interested in TS :fire: :rocket: :man_technologist: :woman_technologist:

**Comment by mhegazy** [comment]
Let's leave it open, other interested users can contribute a fix.
