### ISSUE TITLE
Document Utility Types (Predefined types) 

### ISSUE THREAD

**Issue by chrissantos1995** [Microsoft/TypeScript-Handbook#798]
Opening this issue in response to https://github.com/Microsoft/TypeScript/issues/24558. 

I am currently working on a PR to add a new page to the Handbook titled **Utility Types** (open to suggestions on the title & location of this documentation).

Note that **Utility Types** is a natural name for these utilities as it's the name [adopted by Flow](https://flow.org/en/docs/types/utilities/), and more importantly, it's the terminology originally used in the [release notes](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-1.html#partial-readonly-record-and-pick) for TS 2.1 to describe several of these utilities.

This PR will document the utility types below:

- [ ] `Partial<T>`
- [ ] `Readonly<T>`
- [ ] `Record<K, T>`
- [ ] `Pick<T, K>`
- [ ] `Exclude<T, U>`
- [ ] `Extract<T, U>`
- [ ] `NonNullable<T>`
- [ ] `ReturnType<T>`
- [ ] `InstanceType<T>`
- [ ] `Required<T>`
- [ ] `ThisType<T>` (would resolve #649)

Feedback appreciated!

**Comment by foisonocean** [comment]
Hi @chrissantos1995 @RyanCavanaugh 
I notice although the PR is merged, I can't find the utility types docs in [typescript homepage](https://www.typescriptlang.org/docs/home.html) in anywhere. But actually that docs can be opened by manually typed url "https://www.typescriptlang.org/docs/handbook/utility-types.html".
I guess something is missing in the static site builder config?

**Comment by posva** [comment]
This can be closed now that https://www.typescriptlang.org/docs/handbook/utility-types.html exists

**Comment by karlhorky** [comment]
@foisonocean the side navigation has been updated as of https://github.com/microsoft/TypeScript-Website/pull/1.
