### ISSUE TITLE
Copy-edit all existing content for Markdown compliance

### ISSUE THREAD

**Issue by RyanCavanaugh** [Microsoft/TypeScript-Handbook#8]
I did a rough transition from CodePlex wiki to Markdown, but we need to do a detailed scan of each page to look for any formatting problems.

- [x] Two spaces after periods
- [x] Language tags after triple-ticks (need a bunch of these)
- [ ] Headings level (standardize on one-hash as top-level heading size)
- [ ] Fix link formatting

**Comment by RyanCavanaugh** [comment]
Things to watch out for:
 * Two spaces after periods
 * Language tags after triple-ticks (need a bunch of these)
 * Headings level (standardize on one-hash as top-level heading size)

Edit this comment with more as you see them

**Comment by DanielRosenwasser** [comment]
I've turned this issue into a task list.

**Comment by mhegazy** [comment]
should be fixed now.
