### ISSUE TITLE
The "composite" tsconfig option is not explicitly documented anywhere

### ISSUE THREAD

**Issue by robcresswell** [Microsoft/TypeScript-Handbook#815]
A `tsconfig.json` generated by `tsc --init` contains an entry `"composite": true` under `compilerOptions`, with the comment that this "enables project compilation". The option itself is not mentioned in either https://www.typescriptlang.org/docs/handbook/compiler-options.html or https://www.typescriptlang.org/docs/handbook/tsconfig-json.html and the website itself appears to lack any search function. Whilst I've no doubt the explanation is obvious to people familiar with TS terminology, I'm a little clueless about what "project" is referring to.

Could somebody possibly elaborate on what this setting is doing?

**Comment by chrissantos1995** [comment]
Documentation for this new setting (introduced in 3.0) can be found in [Project References](https://www.typescriptlang.org/docs/handbook/project-references.html#composite):

> Referenced projects must have the new `composite` setting enabled. This setting is needed to ensure TypeScript can quickly determine where to find the outputs of the referenced project. Enabling the `composite` flag changes a few things:
> 
> * The `rootDir` setting, if not explicitly set, defaults to the directory containing the`tsconfig` file
> * All implementation files must be matched by an `include` pattern or listed in the `files` array. If this constraint is violated, `tsc` will inform you which files weren’t specified
> * `declaration` must be turned on
> 
But I agree we should provide info (or at least point to the link above) in the documentation for tsconfig / Compiler Options

**Comment by robcresswell** [comment]
Thanks @chrissantos1995 that's a great help for now; and agreed a reference would be very useful

**Comment by andrewnester** [comment]
I've created PR updating documentation
https://github.com/Microsoft/TypeScript-Handbook/pull/858

**Comment by GongT** [comment]
But what is "Referenced project" 🤔
