### ISSUE TITLE
Add an out of date notice

### ISSUE THREAD

**Issue by slikts** [Microsoft/TypeScript-Handbook#86]
The handbook currently doesn't mention things like tuples, and this makes it confusing if you learn about tuples from a different source and then try to look them up in the handbook. The handbook is also the main form of documentation in the TS website, so it's natural to expect it being up to date, which is an another reason to add a notice that it doesn't cover all the TS features.

**Comment by mhegazy** [comment]
I think we are better served by adding stubbed out paged for some of these topics, or just something like https://github.com/Microsoft/TypeScript/wiki/What%27s-new-in-TypeScript as a skeleton.

**Comment by sandersn** [comment]
I've been working with tuples lately; I'll add a short explanation of tuples and destructuring to the handbook.
