### ISSUE TITLE
Not work

### ISSUE THREAD

**Issue by AKSSINC** [Microsoft/TypeScript-Handbook#922]
**No pdf produced, Windows 10:**

> typescript-handbook-to-pdf@1.0.0 start C:\Work\git\typescript-handbook-to-pdf
> npm run build && npm run execute
> typescript-handbook-to-pdf@1.0.0 build C:\Work\git\typescript-handbook-to-pdf
> parcel build --public-url ./ --target=node src/index.ts
√  Built in 263ms.
dist\index.js     3.56 KB    106ms
dist\index.map        0 B    105ms
> typescript-handbook-to-pdf@1.0.0 execute C:\Work\git\typescript-handbook-to-pdf
> node dist/index

Cloning handbook repo...
(node:21816) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: spawn rm ENOENT
(node:21816) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will te
rminate the Node.js process with a non-zero exit code.

**Comment by DanielRosenwasser** [comment]
Sounds like this is an external problem unless there's something simple to make external tools work better.
