### ISSUE TITLE
Project References Unclear Section

### ISSUE THREAD

**Issue by richsoni** [Microsoft/TypeScript-Handbook#949]
Thanks for the great work here on these docs.  I am currently reading: https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Project%20References.md

I am struggling with this section:
```
When you reference a project, new things happen:
* Importing modules from a referenced project will instead load its output declaration file (.d.ts)
* If the referenced project produces an outFile, the output file .d.ts file's declarations will be visible in this project
* Build mode (see below) will automatically build the referenced project if needed
```
Specifically the following:
 `instead load its output declaration file (.d.ts)` instead of what?  What is the benefit of this?

**Comment by sgronblo** [comment]
I'm not one of the original writers but my guess would be that it's much more efficient to read in a declaration file. With a normal .ts file the compiler might need to read in a whole function including its definition and do type inference to figure out what it's type is.

So your util.ts file would contain something like:

```
function f(a, b, c) {
  // long implementation featuring lots of operations using a,b,c and multiple return points of different type
}
```

When the compiler has analyzed the function though it has an understanding of the types and your .d.ts file will end up containing only:

```
function f (a: string, b: number, c: boolean): string | number
```

This can be read in immediately without doing the same complicated analysis again.

Maybe somebody can correct me if this is incorrect or add if I am missing something.

**Comment by richsoni** [comment]
@sgronblo I agree.  That makes more sense to me.  I opened this https://github.com/Microsoft/TypeScript-Handbook/compare/master...richsoni:patch-1 with wording that adds some clarity that hung me up the first read through

**Comment by richsoni** [comment]
going to close this, and move the conversation to that PR
