### ISSUE TITLE
Typo in readme

### ISSUE THREAD

**Issue by yuxuan-ji** [Microsoft/TypeScript-Handbook#968]
In the How to Contribute section of the readme,
"See our CONTRIBTUTING file for more information - it also..."
CONTRIBTUTING - > CONTRIBUTING

**Comment by parammittal16** [comment]
@yuxuan-ji can i do this ??

**Comment by parammittal16** [comment]
@yuxuan-ji plz review I have open the PR!

**Comment by yuxuan-ji** [comment]
@parammittal16 Thanks for working on it, looks good to me. You can wait for the maintainer to review :)

**Comment by parammittal16** [comment]
ok @yuxuan-ji :)
