### ISSUE TITLE
Utility Types pages is not discoverable

### ISSUE THREAD

**Issue by mweststrate** [microsoft/TypeScript-Handbook#994]
PR #801 introduced a documentation page for the utility types, which closed #798 and #649. However, that page is not publicly reachable (or at least couldn't find a link to it). From the PR I deducted that the correct link is https://www.typescriptlang.org/docs/handbook/utility-types.html, which does work indeed. 

However, it would be great if it that link was part of the main navigation under "handbook"

**Comment by orta** [comment]
This is being deployed right now, thanks!
